export interface Proverb {
  id: number;
  text: string;
  meaning: string;
  category?: string[];
  tags?: string[];
  difficulty?: 'easy' | 'medium' | 'hard';
}

// 100개의 한국 속담 데이터
export const PROVERBS_DATA: Proverb[] = [
  { id: 1, text: "가는 날이 장날이다", meaning: "뜻하지 않은 일이 우연하게도 잘 들어 맞았을 때 쓰는 말.", category: ["우연", "일치"], difficulty: "easy" },
  { id: 2, text: "가는 말이 고와야 오는 말이 곱다", meaning: "내가 남에게 좋게 해야 남도 내게 잘 한다는 말.", category: ["인간관계", "소통"], difficulty: "easy" },
  { id: 3, text: "가랑비에 옷 젖는 줄 모른다", meaning: "재산 같은 것이 조금씩 조금씩 없어지는 줄 모르게 줄어 들어가는 것을 뜻함.", category: ["경계", "주의"], difficulty: "medium" },
  { id: 4, text: "가랑잎이 솔잎더러 바스락거린다고 한다", meaning: "제 결점이 큰 줄 모르고 남의 작은 허물을 탓한다는 말.", category: ["자기반성", "비판"], difficulty: "medium" },
  { id: 5, text: "가재는 게 편이다", meaning: "됨됨이나 형편이 비슷하고 인연 있는 것끼리 서로 편이 되어 어울리고 사정을 보아 준다는 말.", category: ["유유상종", "관계"], difficulty: "easy" },
  { id: 6, text: "가지 많은 나무에 바람 잘 날 없다", meaning: "자식 많은 사람은 걱정이 떠날 때가 없다는 뜻.", category: ["걱정", "가족"], difficulty: "easy" },
  { id: 7, text: "간에 가 붙고 쓸개에 가 붙는다", meaning: "제게 조금이라도 이로운 일이라면 체면과 뜻을 어기고, 아무에게나 아첨한다는 뜻.", category: ["아첨", "이기심"], difficulty: "medium" },
  { id: 8, text: "간에 기별도 안 간다", meaning: "음식을 조금밖에 먹지 못하여 제 양에 차지 않을 때 쓰는 말.", category: ["부족함", "양"], difficulty: "medium" },
  { id: 9, text: "간이 콩알만 해지다", meaning: "겁이 나서 몹시 두려워진다는 뜻.", category: ["두려움", "공포"], difficulty: "easy" },
  { id: 10, text: "갈수록 태산", meaning: "어려운 일을 당하면 당할수록 점점 어려운 일이 닥쳐 온다는 뜻.", category: ["어려움", "시련"], difficulty: "medium" },
  { id: 11, text: "값싼 것이 비지떡", meaning: "무슨 물건이고 값이 싸면 품질이 좋지 못하다는 뜻.", category: ["가치", "품질"], difficulty: "easy" },
  { id: 12, text: "같은 값이면 다홍치마", meaning: "이왕 같은 값이면 자기에게 소득이 많은 것으로 택한다는 말.", category: ["선택", "이익"], difficulty: "easy" },
  { id: 13, text: "개구리 올챙이 적 생각을 못 한다", meaning: "자기의 지위가 높아지면 전날의 미천하던 때의 생각을 못 한다는 뜻.", category: ["교만", "망각"], difficulty: "medium" },
  { id: 14, text: "개밥에 도토리", meaning: "여럿 속에 어울리지 못하는 사람을 뜻하는 말.", category: ["부적응", "소외"], difficulty: "easy" },
  { id: 15, text: "개천에서 용 난다", meaning: "변변하지 못한 집안에서 훌륭한 인물이 나왔을 때 쓰는 말.", category: ["성공", "출세"], difficulty: "easy" },
  { id: 16, text: "고기는 씹어야 맛이요, 말은 해야 맛이라", meaning: "마음속으로만 끙끙거리고 애타하지 말고 할 말은 속 시원히 해야 한다는 말.", category: ["소통", "표현"], difficulty: "medium" },
  { id: 17, text: "고래 싸움에 새우 등 터진다", meaning: "힘센 사람들끼리 서로 싸우는 통에 공연히 약한 사람이 그 사이에 끼여 아무 관계없이 해를 입을 때 쓰는 말.", category: ["피해", "권력"], difficulty: "easy" },
  { id: 18, text: "고양이 목에 방울 달기", meaning: "실행하기 어려운 일을 공연히 의논함을 빗대어 이르는 말.", category: ["실현불가", "공론"], difficulty: "medium" },
  { id: 19, text: "공든 탑이 무너지랴", meaning: "힘을 다하고 정성을 다하여 한 일은 헛되지 않아 반드시 좋은 결과를 얻는다는 뜻.", category: ["노력", "성과"], difficulty: "easy" },
  { id: 20, text: "구더기 무서워 장 못 담글까", meaning: "다소 방해되는 일이 있다 하더라도 마땅히 할 일은 해야 한다는 말.", category: ["의무", "책임"], difficulty: "medium" },
  { id: 21, text: "구슬이 서 말이라도 꿰어야 보배라", meaning: "아무리 훌륭한 일이라도 완전히 끝을 맺어 놓아야 비로소 가치가 있다는 말.", category: ["완성", "가치"], difficulty: "easy" },
  { id: 22, text: "귀에 걸면 귀걸이, 코에 걸면 코걸이", meaning: "한 가지의 것이 이런 것도 같고 저런 것도 같아 어느 한 쪽으로 결정짓기 어려운 일을 두고 하는 말.", category: ["애매함", "결정"], difficulty: "medium" },
  { id: 23, text: "그림의 떡", meaning: "보기는 하여도 먹을 수도 없고 가질 수도 없어 실제에 아무 소용이 없는 경우를 이르는 말.", category: ["실현불가", "허상"], difficulty: "easy" },
  { id: 24, text: "금강산도 식후경", meaning: "아무리 좋은 것, 재미있는 일이 있더라도 배가 부르고 난 뒤에야 좋은 줄 안다. 곧, 먹지 않고는 좋은 줄 모른다는 뜻.", category: ["우선순위", "기본"], difficulty: "easy" },
  { id: 25, text: "뛰는 놈 위에 나는 놈 있다", meaning: "아무리 재주가 있다 하여도 그보다 나은 사람이 있는 것이니 너무 자랑하지 말라는 뜻.", category: ["겸손", "경쟁"], difficulty: "easy" },
  { id: 26, text: "까마귀 날자 배 떨어진다", meaning: "아무 관계없이 한 일이 공교롭게도 다른 일과 때를 같이 하여 둘 사이에 무슨 관계라도 있는 듯한 의심을 받을 때 쓰는 말.", category: ["우연", "오해"], difficulty: "medium" },
  { id: 27, text: "꿩 대신 닭", meaning: "자기가 쓰려는 것이 없을 때, 그와 비슷한 것으로 대신 쓸 수도 있다는 말.", category: ["대체", "현실"], difficulty: "easy" },
  { id: 28, text: "꿩 먹고 알 먹기", meaning: "한 가지 일을 하고 두 가지 이익을 볼 때 쓰는 말.", category: ["이익", "효율"], difficulty: "easy" },
  { id: 29, text: "남의 잔치에 감 놓아라 배 놓아라 한다", meaning: "쓸데없이 남의 일에 간섭한다는 뜻.", category: ["간섭", "참견"], difficulty: "medium" },
  { id: 30, text: "낫 놓고 기역 자도 모른다", meaning: "글자라고는 아무것도 모르는 몹시 무식한 사람을 두고 하는 말.", category: ["무지", "무식"], difficulty: "easy" },
  { id: 31, text: "낮말은 새가 듣고 밤말은 쥐가 듣는다", meaning: "아무리 비밀히 하는 말도 새어 나가기 쉬우니, 말을 항상 조심해서 하라는 뜻.", category: ["비밀", "조심"], difficulty: "easy" },
  { id: 32, text: "내 코가 석자", meaning: "내 사정이 급해서 남의 사정까지 돌볼 수가 없다는 말.", category: ["자기중심", "급함"], difficulty: "easy" },
  { id: 33, text: "누워서 침 뱉기", meaning: "남을 해치려다 도리어 자기 자신이 해를 입는다는 말.", category: ["자업자득", "역효과"], difficulty: "medium" },
  { id: 34, text: "늦게 배운 도둑이 날 새는 줄 모른다", meaning: "나이 들어서 시작한 일에 몹시 골몰한 사람을 두고 이름.", category: ["학습", "열정"], difficulty: "medium" },
  { id: 35, text: "다 된 축에 코 풀기", meaning: "다 된 일을 망쳐 놓았다는 뜻.", category: ["실패", "방해"], difficulty: "medium" },
  { id: 36, text: "달면 삼키고 쓰면 뱉는다", meaning: "제게 이로우면 이용하며, 필요하지 않을 때에는 버린다는 뜻.", category: ["이기심", "처세"], difficulty: "medium" },
  { id: 37, text: "닭 잡아먹고 오리발 내민다", meaning: "나쁜 일을 하고 간사한 꾀로 숨기려 할 때 쓰는 말.", category: ["거짓", "변명"], difficulty: "easy" },
  { id: 38, text: "도둑이 제발 저리다", meaning: "죄지은 자가 그것이 폭로될까 두려워하는 나머지 알지 못하는 가운데 그것을 나타내고야 만다는 뜻.", category: ["자백", "심리"], difficulty: "medium" },
  { id: 39, text: "돌다리도 두들겨 보고 건너라", meaning: "아무리 잘 아는 일이라도 조심하여 실수 없게 하라는 뜻.", category: ["조심", "준비"], difficulty: "easy" },
  { id: 40, text: "되로 주고 말로 받는다", meaning: "남을 조금 건드렸다가 도리어 일을 크게 당한다는 뜻.", category: ["인과", "보복"], difficulty: "medium" },
  { id: 41, text: "등잔 밑이 어둡다", meaning: "제게 가까운 일을 먼 데 일보다 오히려 모른다는 뜻.", category: ["관찰", "주의"], difficulty: "medium" },
  { id: 42, text: "땅 짚고 헤엄치기", meaning: "땅을 짚고 헤엄치듯이 아주 쉽게 할 수 있는 일을 가리켜 하는 말.", category: ["용이함", "쉬움"], difficulty: "easy" },
  { id: 43, text: "똥 묻은 개가 겨 묻은 개 나무란다", meaning: "자기는 더 큰 흉이 있으면서 도리어 남의 작은 흉을 탓한다는 뜻.", category: ["위선", "비판"], difficulty: "easy" },
  { id: 44, text: "마른하늘에 날벼락", meaning: "뜻밖에 입는 재난을 이르는 말.", category: ["불운", "재난"], difficulty: "medium" },
  { id: 45, text: "말 한마디에 천 냥 빚도 갚는다", meaning: "말을 잘 하면 큰 빚도 갚을 수 있다는 말로, 말의 중요성을 나타낸 말.", category: ["소통", "지혜"], difficulty: "easy" },
  { id: 46, text: "목구멍이 포도청", meaning: "먹고살기 위해서는 어떤 일이라도 하게 된다는 뜻.", category: ["생존", "필요"], difficulty: "medium" },
  { id: 47, text: "못된 송아지 엉덩이에 뿔 난다", meaning: "되지 못한 사람이 건방지고 좋지 못한 짓을 한다는 뜻.", category: ["건방짐", "행동"], difficulty: "medium" },
  { id: 48, text: "믿는 도끼에 발등 찍힌다", meaning: "믿던 일이 뜻밖에 실패한다는 말.", category: ["배신", "실망"], difficulty: "easy" },
  { id: 49, text: "밑 빠진 독에 물 붓기", meaning: "아무리 노력을 하고 애써도 보람이 나타나지 않는 경우에 쓰는 말.", category: ["헛수고", "무익"], difficulty: "easy" },
  { id: 50, text: "바늘 도둑이 소 도둑 된다", meaning: "나쁜 행실일수록 점점 더 크고 심하게 되니 아예 나쁜 버릇은 길들이지 말라는 뜻.", category: ["교훈", "경계"], difficulty: "easy" },
  { id: 51, text: "배보다 배꼽이 더 크다", meaning: "마땅히 작아야 할 것이 오히려 클 때를 비유해서 이르는 말.", category: ["본말전도", "균형"], difficulty: "easy" },
  { id: 52, text: "백지장도 맞들면 낫다", meaning: "아무리 쉬운 일이라도 혼자 하는 것보다 협력하여 하는 것이 훨씬 더 낫다는 말.", category: ["협력", "단결"], difficulty: "easy" },
  { id: 53, text: "벼룩의 간 빼먹기", meaning: "극히 적은 이익을 부당한 수단을 써서 착취한다는 말.", category: ["착취", "탐욕"], difficulty: "medium" },
  { id: 54, text: "병 주고 약 준다", meaning: "일이 안 되도록 방해하고는 도와주는 척한다는 뜻.", category: ["위선", "가식"], difficulty: "easy" },
  { id: 55, text: "보기 좋은 떡이 먹기도 좋다", meaning: "겉모양이 좋으면 속의 내용도 좋다는 뜻.", category: ["외관", "내용"], difficulty: "easy" },
  { id: 56, text: "빛 좋은 개살구", meaning: "겉만 번지르하고 실속이 없다는 뜻.", category: ["허세", "실속"], difficulty: "medium" },
  { id: 57, text: "사공이 많으면 배가 산으로 올라간다", meaning: "간섭하는 사람이 많으면 일이 잘 안된다는 뜻.", category: ["협력", "리더십"], difficulty: "medium" },
  { id: 58, text: "새 발의 피", meaning: "지극히 적은 분량을 말함.", category: ["양", "적음"], difficulty: "easy" },
  { id: 59, text: "서당 개 삼 년에 풍월을 읊는다", meaning: "무식한 사람이라도 유식한 사람과 같이 오래 지내면 자연히 견문이 생긴다는 말.", category: ["학습", "환경"], difficulty: "medium" },
  { id: 60, text: "세 살 버릇 여든까지 간다", meaning: "어려서부터 좋은 버릇을 들여야 한다는 뜻.", category: ["습관", "교육"], difficulty: "easy" },
  { id: 61, text: "소문난 잔치에 먹을 것 없다", meaning: "소문난 것이 흔히 실지로는 보잘것없다는 말.", category: ["실망", "과장"], difficulty: "easy" },
  { id: 62, text: "소 잃고 외양간 고친다", meaning: "이미 일을 그르치고 난 뒤 뉘우쳐도 소용이 없다는 뜻.", category: ["교훈", "후회"], difficulty: "easy" },
  { id: 63, text: "소뿔도 단김에 빼라 했다", meaning: "어떤 일을 하려고 생각하였으면 망설이지 말고 곧 행동으로 옮기라는 뜻.", category: ["결단", "행동"], difficulty: "medium" },
  { id: 64, text: "수박 겉핥기", meaning: "내용이나 참뜻은 모르면서 대충 일하는 것을 비유해서 쓰는 말.", category: ["피상적", "불성실"], difficulty: "easy" },
  { id: 65, text: "식은 죽 먹기", meaning: "어떤 일이 아주 하기 쉽다는 말.", category: ["용이함", "쉬움"], difficulty: "easy" },
  { id: 66, text: "십 년이면 강산도 변한다", meaning: "십 년이란 세월이 흐르면 세상에 변하지 않는 것이 없다는 말.", category: ["변화", "시간"], difficulty: "easy" },
  { id: 67, text: "아는 길도 물어가라", meaning: "아무리 익숙한 일이라도 남에게 물어보고 조심함이 안전하다는 뜻.", category: ["조심", "확인"], difficulty: "easy" },
  { id: 68, text: "아니 땐 굴뚝에 연기 나랴", meaning: "반드시 원인이 있어야 결과가 생긴다는 뜻.", category: ["인과", "원인"], difficulty: "medium" },
  { id: 69, text: "아닌 밤중에 홍두깨", meaning: "예고도 없이 뜻밖의 일이 생겼을 때 하는 말.", category: ["의외", "놀람"], difficulty: "medium" },
  { id: 70, text: "약방에 감초", meaning: "어떤 일에나 빠진 없이 참여하는 사람을 말함.", category: ["참여", "존재감"], difficulty: "easy" },
  { id: 71, text: "어물전 망신은 꼴뚜기가 시킨다", meaning: "못난 자일수록 그와 같이 있는 동료를 망신시킨다는 말.", category: ["망신", "책임"], difficulty: "medium" },
  { id: 72, text: "열 길 물속은 알아도 한 길 사람 속은 모른다", meaning: "사람의 마음은 알아내기가 어렵다는 뜻.", category: ["인간심리", "이해"], difficulty: "medium" },
  { id: 73, text: "열 번 찍어 아니 넘어가는 나무 없다", meaning: "여러 번 계속해서 애쓰면 어떤 일이라도 이룰 수 있다는 뜻.", category: ["인내", "노력"], difficulty: "easy" },
  { id: 74, text: "오뉴월 감기는 개도 아니 않는다", meaning: "여름철에 감기 걸린 사람을 조롱하는 말.", category: ["조롱", "건강"], difficulty: "easy" },
  { id: 75, text: "오르지 못할 나무는 쳐다보지도 말아라", meaning: "될 수 없는 일은 바라지도 말라는 뜻.", category: ["현실", "포기"], difficulty: "easy" },
  { id: 76, text: "옥에 티", meaning: "아무리 좋아도 한 가지 결점은 있다는 말.", category: ["결점", "완벽"], difficulty: "easy" },
  { id: 77, text: "우물에 가서 숭늉 찾는다", meaning: "일의 순서도 모르고 성급하게 덤빈다는 뜻.", category: ["순서", "성급함"], difficulty: "medium" },
  { id: 78, text: "울며 겨자 먹기", meaning: "싫은 일을 좋은 척하고 억지로 하지 않을 수 없는 경우를 나타내는 말.", category: ["강제", "어쩔수없음"], difficulty: "easy" },
  { id: 79, text: "원수는 외나무다리에서 만난다", meaning: "남에게 악한 일을 하면 그 죄를 받을 때가 반드시 온다는 뜻.", category: ["인과", "보복"], difficulty: "medium" },
  { id: 80, text: "원숭이도 나무에서 떨어진다", meaning: "아무리 능숙한 사람도 실수할 때가 있다는 말.", category: ["실수", "겸손"], difficulty: "easy" },
  { id: 81, text: "윗물이 맑아야 아랫물도 맑다", meaning: "윗사람이 잘못하면 아랫사람도 따라서 잘못하게 된다는 뜻.", category: ["영향", "모범"], difficulty: "easy" },
  { id: 82, text: "자라 보고 놀란 가슴 솥뚜껑 보고 놀란다", meaning: "무엇에 한 번 혼난 사람이 그와 비슷한 것만 보아도 깜짝 놀란다는 말.", category: ["트라우마", "경험"], difficulty: "medium" },
  { id: 83, text: "자랄 나무는 떡잎부터 알아본다", meaning: "앞으로 크게 될 사람은 어려서부터 장래성이 엿보인다는 말.", category: ["잠재력", "성장"], difficulty: "easy" },
  { id: 84, text: "작은 고추가 더 맵다", meaning: "겉으로는 대수롭지 않게 보이는 사람이 하는 일이 더 다부지다는 뜻.", category: ["외관", "실력"], difficulty: "easy" },
  { id: 85, text: "종로에서 뺨 맞고 한강 가서 눈 흘긴다", meaning: "욕을 당한 자리에서는 아무 말도 못 하고 딴 데 가서 화풀이를 한다는 뜻.", category: ["분노", "무력함"], difficulty: "medium" },
  { id: 86, text: "좋은 약은 입에 쓰다", meaning: "듣기 싫고 귀에 거슬리는 말이라도 제 인격 수양에는 이롭다는 뜻.", category: ["충고", "성장"], difficulty: "medium" },
  { id: 87, text: "쥐구멍에도 볕 들 날이 있다", meaning: "아무리 고생만 하는 사람도 운수가 터져 좋은 시기를 만날 때가 있다는 말.", category: ["희망", "기회"], difficulty: "easy" },
  { id: 88, text: "지렁이도 밟으면 꿈틀한다", meaning: "아무리 보잘것없는 사람이라도 너무나 업신여기면 성을 낸다는 뜻.", category: ["존중", "반발"], difficulty: "easy" },
  { id: 89, text: "천 리 길도 한 걸음부터", meaning: "무슨 일이든 그 시초가 중요하다는 뜻.", category: ["시작", "과정"], difficulty: "easy" },
  { id: 90, text: "칼로 물 베기", meaning: "다투다가도 좀 시간이 흐르면 이내 풀려 두 사람 사이에 아무 틈이 생기지 않는다는 뜻.", category: ["화해", "관계"], difficulty: "medium" },
  { id: 91, text: "콩 심은 데 콩 나고 팥 심은 데 팥 난다", meaning: "모든 일은 원인에 따라 결과가 생긴다는 말.", category: ["인과", "결과"], difficulty: "easy" },
  { id: 92, text: "티끌 모아 태산", meaning: "작은 것이라도 모이면 큰 것이 된다는 뜻.", category: ["축적", "성장"], difficulty: "easy" },
  { id: 93, text: "핑계 없는 무덤 없다", meaning: "무엇을 잘못해 놓고도 여러 가지 이유로 책임을 회피하려는 사람을 두고 하는 말.", category: ["변명", "책임회피"], difficulty: "easy" },
  { id: 94, text: "하늘의 별 따기", meaning: "지극히 어려운 일을 두고 하는 말.", category: ["난이도", "불가능"], difficulty: "easy" },
  { id: 95, text: "하늘이 무너져도 솟아날 구멍이 있다", meaning: "아무리 큰 재난에 부딪히더라도 그것에서 벗어날 길은 있다는 뜻.", category: ["희망", "해결책"], difficulty: "medium" },
  { id: 96, text: "하룻강아지 범 무서운 줄 모른다", meaning: "아직 철이 없어서 아무것도 모르는 것을 두고 하는 말.", category: ["경험", "무지"], difficulty: "easy" },
  { id: 97, text: "한 귀로 듣고 한 귀로 흘린다", meaning: "남이 애써 일러 주는 말을 유념해서 듣지 않고 건성으로 듣는 것을 이름.", category: ["무관심", "경청"], difficulty: "easy" },
  { id: 98, text: "한 술 밥에 배부르랴", meaning: "무슨 일이고 처음에는 큰 성과를 기대할 수 없다는 말, 힘을 조금 들이고는 큰 효과를 바랄 수 없다는 이야기.", category: ["과정", "인내"], difficulty: "medium" },
  { id: 99, text: "함흥차사라", meaning: "어떤 일로 심부름 간 사람이 한 번 떠난 뒤로 돌아오지 않거나 아무 소식이 없다는 뜻.", category: ["소식", "실종"], difficulty: "medium" },
  { id: 100, text: "호랑이도 제 말 하면 온다", meaning: "마침 이야기하고 있는데 그 장본인이 나타났을 때 하는 말로, 자리에 사람이 없다고 하여 남의 흉을 함부로 보지 말라는 뜻.", category: ["조심", "우연"], difficulty: "easy" }
]; 