import { QuizQuestion } from "@/types"

export const PICTURE_QUIZ_DATA: QuizQuestion[] = [
  {
    id: "picture-1",
    question: "이 그림은 어떤 속담을 나타낼까요?",
    answer: "가뭄에 콩 나듯 한다",
    explanation: "어떤 일이나 물건이 드문드문 있을 때 하는 말입니다.",
    imageUrl: "/placeholder.svg",
    options: ["가뭄에 콩 나듯 한다", "가뭄에 단비", "가뭄에 비", "가뭄에 우물 파기"],
  },
  {
    id: "picture-2",
    question: "이 그림은 어떤 속담을 나타낼까요?",
    answer: "굴러 온 호박이다",
    explanation: "어디선가 호박이 굴러오듯이 뜻밖에 횡재하게 되었다는 말입니다.",
    imageUrl: "/placeholder.svg",
    options: ["굴러 온 호박이다", "굴러 온 돌이 박힌 돌 뺀다", "굴러 온 복", "굴러 온 행운"],
  },
  {
    id: "picture-3",
    question: "이 그림은 어떤 속담을 나타낼까요?",
    answer: "굼벵이도 뒹구는 재주가 있다",
    explanation: "아무리 미련하고 못난 사람이라도 생명만은 이어 갈 수 있다는 말입니다.",
    imageUrl: "/placeholder.svg",
    options: ["굼벵이도 뒹구는 재주가 있다", "굼벵이도 밟으면 꿈틀거린다", "굼벵이도 살아간다", "굼벵이도 제 살길 찾는다"],
  },
  {
    id: "picture-4",
    question: "이 그림은 어떤 속담을 나타낼까요?",
    answer: "궁지에 몰린 쥐가 고양이를 문다",
    explanation: "아무리 약한 놈이라도 죽을 지경에 이르면 강적에게 용기를 내어 달려든다는 말입니다.",
    imageUrl: "/placeholder.svg",
    options: ["궁지에 몰린 쥐가 고양이를 문다", "고양이 앞에 쥐", "쥐구멍에도 볕 들 날 있다", "쥐도 궁하면 고양이를 문다"],
  },
  {
    id: "picture-5",
    question: "이 그림은 어떤 속담을 나타낼까요?",
    answer: "귀에 걸면 귀걸이 코에 걸면 코걸이",
    explanation: "정해 놓은 것이 아니고 둘러 댈 탓이라는 뜻입니다.",
    imageUrl: "/placeholder.svg",
    options: ["귀에 걸면 귀걸이 코에 걸면 코걸이", "귀와 코는 가까운 이웃", "귀에 걸고 코에 걸고", "귀에 들어도 코에서 나온다"],
  },
  {
    id: "picture-6",
    question: "이 그림은 어떤 속담을 나타낼까요?",
    answer: "그물에 든 고기",
    explanation: "이미 잡힌 몸이 되어 벗어날 수 없는 신세를 말합니다.",
    imageUrl: "/placeholder.svg",
    options: ["그물에 든 고기", "그물에 걸린 물고기", "그물에 걸린 새", "그물에 걸린 짐승"],
  },
  {
    id: "picture-7",
    question: "이 그림은 어떤 속담을 나타낼까요?",
    answer: "기는 놈 위에 나는 놈 있다",
    explanation: "잘하는 사람위에 더 잘하는 사람이 있으니 너무 자랑 말라는 뜻입니다.",
    imageUrl: "/placeholder.svg",
    options: ["기는 놈 위에 나는 놈 있다", "기는 놈 위에 서는 놈 있다", "기는 놈 위에 달리는 놈 있다", "기는 놈 위에 걷는 놈 있다"],
  },
  {
    id: "picture-8",
    question: "이 그림은 어떤 속담을 나타낼까요?",
    answer: "김칫국부터 마신다",
    explanation: "줄 사람은 생각도 안 하는데 받을 쪽에서 공연히 서두르며 덤빈다는 의미입니다.",
    imageUrl: "/placeholder.svg",
    options: ["김칫국부터 마신다", "김칫국도 없는데 숟가락 든다", "김칫국 마시고 얼굴 붉히다", "김칫국 마시고 배부르다"],
  },
  {
    id: "picture-9",
    question: "이 그림은 어떤 속담을 나타낼까요?",
    answer: "까마귀 날자 배 떨어진다",
    explanation: "엉뚱한 일로 말미암아 억울한 누명을 썼을 때를 두고 이르는 말입니다.",
    imageUrl: "/placeholder.svg",
    options: ["까마귀 날자 배 떨어진다", "까마귀 날자 사과 떨어진다", "까마귀 날자 나무 흔들린다", "까마귀 날자 잎 떨어진다"],
  },
  {
    id: "picture-10",
    question: "이 그림은 어떤 속담을 나타낼까요?",
    answer: "꿩 먹고 알 먹는다",
    explanation: "일거양득, 한거번에 모든 이익을 보는 것을 의미합니다.",
    imageUrl: "/placeholder.svg",
    options: ["꿩 먹고 알 먹는다", "꿩 대신 닭", "꿩 잡는 매", "꿩 먹고 닭 먹는다"],
  },
] 